# 항등함수와 소프트맥스 함수 구현하기

In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)

In [4]:
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [5]:
sum_exp_a = np.sum(exp_a)

In [6]:
print(sum_exp_a)

74.1221542101633


In [7]:
y = exp_a / sum_exp_a

In [8]:
print(y)

[0.01821127 0.24519181 0.73659691]


softmax function

In [9]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

softmax function 구현 시 주의점

In [10]:
a = np.array([1010, 1000, 990])

In [11]:
np.exp(a) / np.sum(np.exp(a))

<ipython-input-11-465cd0a655b6>:1: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-11-465cd0a655b6>:1: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [12]:
c = np.max(a)

In [14]:
a-c

array([  0, -10, -20])

In [16]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])


overflow 대체한 softmax function

In [17]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) #오버플로 대책
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

softmax 함수의 특징

In [18]:
a= np.array([0.3, 2.9, 4.0])

In [19]:
y = softmax(a)

In [21]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [22]:
np.sum(y)

1.0