In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4])

In [3]:
A

array([1, 2, 3, 4])

In [4]:
print(A)

[1 2 3 4]


In [5]:
np.ndim(A)

1

In [6]:
A.shape

(4,)

In [7]:
A.shape[0]

4

In [9]:
import numpy as np

In [12]:
B = np.array([[1, 2], [3, 4], [5, 6]])

In [13]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
np.ndim(B)

2

In [15]:
np.shape(B)

(3, 2)

In [17]:
A = np.array([[1,2], [3,4]])

In [18]:
A.shape

(2, 2)

In [19]:
B = np.array([[5,6], [7,8]])

In [20]:
B.shape

(2, 2)

In [21]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [22]:
A = np.array([[1,2,3],[4,5,6]])

In [23]:
A.shape

(2, 3)

In [25]:
B = np.array([[1,2],[3,4],[5,6]])

In [26]:
B.shape

(3, 2)

In [27]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [28]:
C = np.array([[1,2],[3,4]])

In [29]:
C.shape

(2, 2)

In [30]:
A.shape

(2, 3)

In [31]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
A = np.array([[1,2],[3,4],[5,6]])

In [33]:
A.shape

(3, 2)

In [36]:
B = np.array([7,8])

In [37]:
B.shape

(2,)

In [39]:
np.dot(A,B)

array([23, 53, 83])

In [40]:
X = np.array([1,2])

In [41]:
X.shape

(2,)

In [42]:
W = np.array([[1,3,5],[2,4,6]])

In [43]:
W.shape

(2, 3)

In [44]:
Y = np.dot(X , W)

In [45]:
print(Y)

[ 5 11 17]


In [57]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [58]:
X = np.array([1.0, 0.5])

In [59]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

In [60]:
B1 = np.array([0.1, 0.2, 0.3])

In [61]:
print(W1.shape)

(2, 3)


In [62]:
print(X.shape)

(2,)


In [63]:
print(B1.shape)

(3,)


In [64]:
A1 = np.dot(X,W1) + B1

In [65]:
Z1 = sigmoid(A1)

In [66]:
print(A1)

[0.3 0.7 1.1]


In [67]:
print(Z1)

[0.57444252 0.66818777 0.75026011]


In [68]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])

In [69]:
B2 = np.array([0.1, 0.2])

In [70]:
print(Z1.shape)

(3,)


In [71]:
print(W2.shape)

(3, 2)


In [72]:
print(B2.shape)

(2,)


In [74]:
A2 = np.dot(Z1, W2) + B2

In [76]:
Z2 = sigmoid(A2)

In [77]:
def identity_function(x):
    return x

In [78]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([[0.1, 0.2]])

In [79]:
A3 = np.dot(Z2, W3) + B3

In [80]:
Y = identity_function(A3)

구현 정리

In [85]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

In [88]:
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

In [89]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

In [90]:
print(y)

[0.31682708 0.69627909]
